# Generated by Django 5.2.17 on 2026-09-30 09:51

import django.core.validators
import django.db.models.deletion
import globe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Например: UZ, RU, JP, US. По этому коду на глобусе подсвечиваются границы.', max_length=2, unique=True, verbose_name='Код страны (ISO 3166-1 alpha-2)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (ru)')),
                ('name_uz', models.CharField(blank=True, max_length=200, verbose_name='Название (uz)')),
                ('name_qr', models.CharField(blank=True, max_length=200, verbose_name='Название (qr)')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта центра')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота центра')),
                ('boundary', models.JSONField(blank=True, help_text='Необязательно. Polygon или MultiPolygon в формате GeoJSON.', null=True, verbose_name='Границы (GeoJSON geometry)')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
                'ordering': ['name_ru'],
            },
            bases=(globe.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (ru)')),
                ('name_uz', models.CharField(blank=True, max_length=200, verbose_name='Название (uz)')),
                ('name_qr', models.CharField(blank=True, max_length=200, verbose_name='Название (qr)')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Население (приблизительно)')),
                ('is_capital', models.BooleanField(default=False, verbose_name='Столица государства')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на глобусе')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (ru)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (uz)')),
                ('description_qr', models.TextField(blank=True, verbose_name='Описание (qr)')),
                ('history_ru', models.TextField(blank=True, help_text='Одно событие на строку в формате «Год — событие».', verbose_name='История (ru)')),
                ('history_uz', models.TextField(blank=True, help_text='Формат: «Год — событие».', verbose_name='История (uz)')),
                ('history_qr', models.TextField(blank=True, help_text='Формат: «Год — событие».', verbose_name='История (qr)')),
                ('industry_ru', models.TextField(blank=True, help_text='Одна позиция на строку в формате «Название — описание».', verbose_name='Компании и производство (ru)')),
                ('industry_uz', models.TextField(blank=True, help_text='Формат: «Название — описание».', verbose_name='Компании и производство (uz)')),
                ('industry_qr', models.TextField(blank=True, help_text='Формат: «Название — описание».', verbose_name='Компании и производство (qr)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='globe.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ['name_ru'],
            },
            bases=(globe.models.LocalizedMixin, models.Model),
        ),
    ]
